### PR TITLE
Pet model fixed

### PR DESCRIPTION
**Pull request by vitaliipp**
Pet model fixed, enums removed

### CODE REVIEW

**Comment by Nata-Kalina** [comment]
Are you sure that you have to delete enums, but leave defaults? I thought we discussed deleting defaults.

**Comment by vitaliipp** [comment]
I checked the testing database and it seems that all fields without enums but with defaults work correctly, like images where default values are successfully overwritten.

**Comment by Nata-Kalina** [comment]
I tested new pet model and received the error:
Error: Pet validation failed: user: Please provide user
at ValidationError.inspect (C:\Users\12678\PracticumProject\cc-prac-team4-back\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:806:19)
    at inspect (node:internal/util/inspect:365:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2273:40)
    at formatWithOptions (node:internal/util/inspect:2135:10)
    at console.value (node:internal/console/constructor:340:14)
    at console.log (node:internal/console/constructor:377:61)
    at fetchPetList (C:\Users\12678\PracticumProject\cc-prac-team4-back\src\fetchPetList.js:60:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: {
    user: ValidatorError: Please provide user
        at validate (C:\Users\12678\PracticumProject\cc-prac-team4-back\node_modules\mongoose\lib\schematype.js:1349:13)
        at SchemaType.doValidate (C:\Users\12678\PracticumProject\cc-prac-team4-back\node_modules\mongoose\lib\schematype.js:1333:7)
        at C:\Users\12678\PracticumProject\cc-prac-team4-back\node_modules\mongoose\lib\document.js:2932:18        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'required',
      path: 'user',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'Pet validation failed'
}

**Comment by vitaliipp** [comment]
Fixed, previous user settings committed

**Comment by Nata-Kalina** [comment]
Still receive the same error
Error: Pet validation failed: user: Please provide user
    at ValidationError.inspect (C:\Users\12678\PracticumProject\cc-prac-team4-back\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:806:19)
    at inspect (node:internal/util/inspect:365:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2273:40)
    at formatWithOptions (node:internal/util/inspect:2135:10)
    at console.value (node:internal/console/constructor:340:14)
    at console.log (node:internal/console/constructor:377:61)
    at fetchPetList (C:\Users\12678\PracticumProject\cc-prac-team4-back\src\fetchPetList.js:60:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: {
    user: ValidatorError: Please provide user
        at validate (C:\Users\12678\PracticumProject\cc-prac-team4-back\node_modules\mongoose\lib\schematype.js:1349:13)
        at SchemaType.doValidate (C:\Users\12678\PracticumProject\cc-prac-team4-back\node_modules\mongoose\lib\schematype.js:1333:7)
        at C:\Users\12678\PracticumProject\cc-prac-team4-back\node_modules\mongoose\lib\document.js:2932:18        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'required',
      path: 'user',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'Pet validation failed'
}

**Comment by Nata-Kalina** [comment]
Do you have your last commit here? Sorry, I found it here but I still receive the same error.
Maybe it could be a problem with our fetching file. In our previous branch pet-module-fetch-list fetching file is working fine. Maybe we could merge it to dev without mentor's approval. In that branch it is working, but you took the code from dev and in your code there can be the version of fetching file that doesn't work. I don't know how to synchronize everything while the branch with working fetching file is still not merged to dev. Can't test your model properly

**Comment by vitaliipp** [comment]
the user changed back to createdBy according to the code of your utility fetchPetList.js:
(const pets = petResponse.data.animals.map((animal) => {
      return {
        createdBy: new mongoose.Types.ObjectId(), // Use 'new' keyword to invoke the ObjectId constructor
        description: animal.description || 'No description available', // Use a default value if description is not available
        petName: animal.name || '',)

**Pull request closed without merging**
