### PR TITLE
Tasks: PP-25, PP-32, PP-33, PP-35, PP-36, PP-37, PP-44. 

### PR DESCRIPTION
**Pull request by Nata-Kalina**
User module initial setup.

### CODE REVIEW

**Comment by Nata-Kalina** [comment]
Not everything is working fine.
Forgot password and Reset password functionalities both don't work. Try to fix it later.
Admin routs when unauthenticated throws not my nice error, but other ugly error.
Smoke tests were done in Postman, collection was created. 
Not-found middleware was interrupting the connection. Problem was fixed in next commit.

**Review by badgerbadgers — APPROVED** [review]
That's alot of functionality! Great job! Push the fixes when you can.

**Comment by frankstepanski** [comment]
@Nata-Kalina Lot's of great work here but a few things to keep in mind:

- Each PR should represent one feature
- If a PR is not 100% working, it should be in draft mode; so others can help troubleshoot
- Make sure you have sufficient commits per PR; it makes it difficult to follow
- **Note:** If this PR was for one simple feature, you could have 1 commit

**Comment by Nata-Kalina** [comment]
Thank you! I don't know how to separate such functionality on a few features, definitely should learn how to do it. Thank you so much for your time and advices.

**Comment by vitaliipp** [comment]
@Nata-Kalina Great job. But why do you use Server Side Rendering - Handlebars? I think we shouldn't use it in our project.

**Review by vitaliipp — CHANGES_REQUESTED** [review]
Could you split the pull request into smaller ones?
Since our project doesn't utilize server-side rendering (SSR),  remove the Handlebars functionality.
The userController.js file appears to be quite large. I recommend separating the authentication functionality (register, login, logout) into its own module, specifically an authController, and authRouter.

**Review by MunirNuristani — APPROVED** [review]
LGTM! The only thing that I want to point out is to make one PR per task. That way it is easy to follow the changes and easier for everyone to review. Additionally, If a PR introduces a Bug, It would be easier to isolate and revert. 
Great Work. Super impressed by your work.

**Comment by Nata-Kalina** [comment]
@vitaliipp thanks for reviewing! Tried to do the whole module ASAP and didn't have much time to figure out that these features use server side rendering. Definitely will refactor Forgot password and Reset password. This solution doesn't work anyway.

**Review by vitaliipp — APPROVED** [review]

**Pull request merged**
