### PR TITLE
PP-26 Create Pet model

### PR DESCRIPTION
**Pull request by vitaliipp**
Created Pet model and added basic routes: createPet,  getAllPets,  getSinglePet,  updatePet,
deletePet,  uploadImage.

### CODE REVIEW

**Review by OxiBo — CHANGES_REQUESTED** [review]
A lot of  work done here but a few things to keep in mind which was already mentioned in the other pull request - each PR should represent one feature and be easy to follow. Please try to create different branched for each feature and create different PRs for them. 
I recommend using DEV branch as the default branch while in the development.

**Comment by vitaliipp** [comment]
> A lot of work done here but a few things to keep in mind which was already mentioned in the other pull request - each PR should represent one feature and be easy to follow. Please try to create different branched for each feature and create different PRs for them. I recommend using DEV branch as the default branch while in the development.

Thank you for review. I'll try to split the pull request on a few smaller PRs.

**Review by Nata-Kalina — APPROVED** [review]
LGTM

**Review by MunirNuristani — APPROVED** [review]
LGTM! Great work.

**Pull request merged**
